name: Rumrm
on:
 # push:
  #  branches: [ main ]
 # pull_request:
  #  branches: [ main ]
  schedule:
    - cron: '0 23 * * *'
 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 克隆项目
      run: git clone https://github.com/yi985432/Runrm-BK
    - name: 检测网站是否被删除
      run: cd ~/work/Runrm-BK/Runrm-BK/Runrm-BK & sh start.sh
    
    
